// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidationHelper is an autogenerated mock type for the ValidationHelper type
type ValidationHelper struct {
	mock.Mock
}

// CheckInput provides a mock function with given fields: operator, operands
func (_m *ValidationHelper) CheckInput(operator string, operands []float64) error {
	ret := _m.Called(operator, operands)

	if len(ret) == 0 {
		panic("no return value specified for CheckInput")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []float64) error); ok {
		r0 = rf(operator, operands)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewValidationHelper creates a new instance of ValidationHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidationHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidationHelper {
	mock := &ValidationHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
